name: Main workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      LOCAL_VERSION_NUMBER_FILE: build_version.txt
    steps:
    - name: Check out the project
      uses: actions/checkout@v2.3.2
    - name: Set up environment
      run: echo "Set up environment"
    - name: Determine project version
      id: version
      uses: anttikivi/maintain-revision@v0.6.0
      with:
        type: json
        file: package.json
    - name: Cache dependencies
      run: echo "Cache dependencies"
    - name: Install dependencies
      run: echo "Install dependencies"
    - name: Compile
      run: echo "Compile"
    - name: Upload build artefacts
      uses: actions/upload-artifact@v2.1.4
      with:
        name: project-name-${{ steps.version.outputs.version }}
        path: build/*.zip
